/*
 *  tileGtk_Symbols.cpp
 * ------------------------
 *
 * This file is part of the Tile-Gtk package, a Tk/Tile based theme that uses
 * Gtk/GNOME for drawing.
 *
 * Copyright (C) 2004-2008 by:
 * Georgios Petasis, petasis@iit.demokritos.gr,
 * Software and Knowledge Engineering Laboratory,
 * Institute of Informatics and Telecommunications,
 * National Centre for Scientific Research (NCSR) "Demokritos",
 * Aghia Paraskevi, 153 10, Athens, Greece.
 */
/* THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT! */
#include "tileGtk_Symbols.h"
#ifdef    TILEGTK_LOAD_GTK_DYNAMICALLY
#include <gmodule.h>

Ptr_g_free TileGtk_g_free = 0;
Ptr_g_hash_table_get_keys TileGtk_g_hash_table_get_keys = 0;
Ptr_g_malloc TileGtk_g_malloc = 0;
Ptr_g_malloc0 TileGtk_g_malloc0 = 0;
Ptr_g_object_get TileGtk_g_object_get = 0;
Ptr_g_object_unref TileGtk_g_object_unref = 0;
Ptr_g_option_context_add_main_entries TileGtk_g_option_context_add_main_entries = 0;
Ptr_g_option_context_new TileGtk_g_option_context_new = 0;
Ptr_g_strfreev TileGtk_g_strfreev = 0;
Ptr_gdk_color_to_string TileGtk_gdk_color_to_string = 0;
Ptr_gdk_display_get_default TileGtk_gdk_display_get_default = 0;
Ptr_gdk_display_get_screen TileGtk_gdk_display_get_screen = 0;
Ptr_gdk_drawable_set_colormap TileGtk_gdk_drawable_set_colormap = 0;
Ptr_gdk_gc_new TileGtk_gdk_gc_new = 0;
Ptr_gdk_pixbuf_get_from_drawable TileGtk_gdk_pixbuf_get_from_drawable = 0;
Ptr_gdk_pixbuf_new TileGtk_gdk_pixbuf_new = 0;
Ptr_gdk_pixbuf_unref TileGtk_gdk_pixbuf_unref = 0;
Ptr_gdk_pixbuf_xlib_render_to_drawable TileGtk_gdk_pixbuf_xlib_render_to_drawable = 0;
Ptr_gdk_pixmap_foreign_new_for_screen TileGtk_gdk_pixmap_foreign_new_for_screen = 0;
Ptr_gdk_pixmap_new TileGtk_gdk_pixmap_new = 0;
Ptr_gdk_x11_colormap_foreign_new TileGtk_gdk_x11_colormap_foreign_new = 0;
Ptr_gdk_x11_lookup_xdisplay TileGtk_gdk_x11_lookup_xdisplay = 0;
Ptr_gdk_x11_screen_lookup_visual TileGtk_gdk_x11_screen_lookup_visual = 0;
Ptr_gtk_adjustment_new TileGtk_gtk_adjustment_new = 0;
Ptr_gtk_adjustment_set_value TileGtk_gtk_adjustment_set_value = 0;
Ptr_gtk_arrow_new TileGtk_gtk_arrow_new = 0;
Ptr_gtk_border_free TileGtk_gtk_border_free = 0;
Ptr_gtk_button_get_relief TileGtk_gtk_button_get_relief = 0;
Ptr_gtk_button_new TileGtk_gtk_button_new = 0;
Ptr_gtk_button_set_relief TileGtk_gtk_button_set_relief = 0;
Ptr_gtk_check_button_new TileGtk_gtk_check_button_new = 0;
Ptr_gtk_combo_box_entry_new TileGtk_gtk_combo_box_entry_new = 0;
Ptr_gtk_combo_box_new TileGtk_gtk_combo_box_new = 0;
Ptr_gtk_container_add TileGtk_gtk_container_add = 0;
Ptr_gtk_disable_setlocale TileGtk_gtk_disable_setlocale = 0;
Ptr_gtk_entry_new TileGtk_gtk_entry_new = 0;
Ptr_gtk_fixed_new TileGtk_gtk_fixed_new = 0;
Ptr_gtk_frame_new TileGtk_gtk_frame_new = 0;
Ptr_gtk_hpaned_new TileGtk_gtk_hpaned_new = 0;
Ptr_gtk_hscale_new_with_range TileGtk_gtk_hscale_new_with_range = 0;
Ptr_gtk_hscrollbar_new TileGtk_gtk_hscrollbar_new = 0;
Ptr_gtk_init_check TileGtk_gtk_init_check = 0;
Ptr_gtk_notebook_new TileGtk_gtk_notebook_new = 0;
Ptr_gtk_object_get TileGtk_gtk_object_get = 0;
Ptr_gtk_paint_arrow TileGtk_gtk_paint_arrow = 0;
Ptr_gtk_paint_box TileGtk_gtk_paint_box = 0;
Ptr_gtk_paint_box_gap TileGtk_gtk_paint_box_gap = 0;
Ptr_gtk_paint_check TileGtk_gtk_paint_check = 0;
Ptr_gtk_paint_extension TileGtk_gtk_paint_extension = 0;
Ptr_gtk_paint_flat_box TileGtk_gtk_paint_flat_box = 0;
Ptr_gtk_paint_focus TileGtk_gtk_paint_focus = 0;
Ptr_gtk_paint_handle TileGtk_gtk_paint_handle = 0;
Ptr_gtk_paint_option TileGtk_gtk_paint_option = 0;
Ptr_gtk_paint_resize_grip TileGtk_gtk_paint_resize_grip = 0;
Ptr_gtk_paint_shadow TileGtk_gtk_paint_shadow = 0;
Ptr_gtk_paint_slider TileGtk_gtk_paint_slider = 0;
Ptr_gtk_progress_bar_new TileGtk_gtk_progress_bar_new = 0;
Ptr_gtk_progress_bar_set_bar_style TileGtk_gtk_progress_bar_set_bar_style = 0;
Ptr_gtk_progress_bar_set_fraction TileGtk_gtk_progress_bar_set_fraction = 0;
Ptr_gtk_progress_bar_set_orientation TileGtk_gtk_progress_bar_set_orientation = 0;
Ptr_gtk_range_get_adjustment TileGtk_gtk_range_get_adjustment = 0;
Ptr_gtk_rc_get_default_files TileGtk_gtk_rc_get_default_files = 0;
Ptr_gtk_rc_get_style TileGtk_gtk_rc_get_style = 0;
Ptr_gtk_rc_get_theme_dir TileGtk_gtk_rc_get_theme_dir = 0;
Ptr_gtk_rc_reparse_all_for_settings TileGtk_gtk_rc_reparse_all_for_settings = 0;
Ptr_gtk_rc_reset_styles TileGtk_gtk_rc_reset_styles = 0;
Ptr_gtk_rc_set_default_files TileGtk_gtk_rc_set_default_files = 0;
Ptr_gtk_settings_get_default TileGtk_gtk_settings_get_default = 0;
Ptr_gtk_statusbar_new TileGtk_gtk_statusbar_new = 0;
Ptr_gtk_style_apply_default_background TileGtk_gtk_style_apply_default_background = 0;
Ptr_gtk_style_attach TileGtk_gtk_style_attach = 0;
Ptr_gtk_style_lookup_color TileGtk_gtk_style_lookup_color = 0;
Ptr_gtk_toolbar_new TileGtk_gtk_toolbar_new = 0;
Ptr_gtk_vpaned_new TileGtk_gtk_vpaned_new = 0;
Ptr_gtk_vscale_new_with_range TileGtk_gtk_vscale_new_with_range = 0;
Ptr_gtk_vscrollbar_new TileGtk_gtk_vscrollbar_new = 0;
Ptr_gtk_widget_destroy TileGtk_gtk_widget_destroy = 0;
Ptr_gtk_widget_realize TileGtk_gtk_widget_realize = 0;
Ptr_gtk_widget_set_size_request TileGtk_gtk_widget_set_size_request = 0;
Ptr_gtk_widget_size_request TileGtk_gtk_widget_size_request = 0;
Ptr_gtk_widget_style_get TileGtk_gtk_widget_style_get = 0;
Ptr_gtk_window_new TileGtk_gtk_window_new = 0;
Ptr_xlib_rgb_init TileGtk_xlib_rgb_init = 0;

const char* TileGtk_InitialiseSymbols_gdk(const char *file_name) {
  GModule *m = g_module_open(file_name, G_MODULE_BIND_LAZY);
  if (!m) return "module_open";
  if (!g_module_symbol(m, "gdk_color_to_string", (gpointer *) &TileGtk_gdk_color_to_string))
    return "gdk_color_to_string";
  if (!g_module_symbol(m, "gdk_display_get_default", (gpointer *) &TileGtk_gdk_display_get_default))
    return "gdk_display_get_default";
  if (!g_module_symbol(m, "gdk_display_get_screen", (gpointer *) &TileGtk_gdk_display_get_screen))
    return "gdk_display_get_screen";
  if (!g_module_symbol(m, "gdk_drawable_set_colormap", (gpointer *) &TileGtk_gdk_drawable_set_colormap))
    return "gdk_drawable_set_colormap";
  if (!g_module_symbol(m, "gdk_gc_new", (gpointer *) &TileGtk_gdk_gc_new))
    return "gdk_gc_new";
  if (!g_module_symbol(m, "gdk_pixbuf_get_from_drawable", (gpointer *) &TileGtk_gdk_pixbuf_get_from_drawable))
    return "gdk_pixbuf_get_from_drawable";
  if (!g_module_symbol(m, "gdk_pixmap_foreign_new_for_screen", (gpointer *) &TileGtk_gdk_pixmap_foreign_new_for_screen))
    return "gdk_pixmap_foreign_new_for_screen";
  if (!g_module_symbol(m, "gdk_pixmap_new", (gpointer *) &TileGtk_gdk_pixmap_new))
    return "gdk_pixmap_new";
  if (!g_module_symbol(m, "gdk_x11_colormap_foreign_new", (gpointer *) &TileGtk_gdk_x11_colormap_foreign_new))
    return "gdk_x11_colormap_foreign_new";
  if (!g_module_symbol(m, "gdk_x11_lookup_xdisplay", (gpointer *) &TileGtk_gdk_x11_lookup_xdisplay))
    return "gdk_x11_lookup_xdisplay";
  if (!g_module_symbol(m, "gdk_x11_screen_lookup_visual", (gpointer *) &TileGtk_gdk_x11_screen_lookup_visual))
    return "gdk_x11_screen_lookup_visual";
  return 0;
}; /* TileGtk_InitialiseSymbols_gdk */


const char* TileGtk_InitialiseSymbols_gdk_pixbuf(const char *file_name) {
  GModule *m = g_module_open(file_name, G_MODULE_BIND_LAZY);
  if (!m) return "module_open";
  if (!g_module_symbol(m, "gdk_pixbuf_new", (gpointer *) &TileGtk_gdk_pixbuf_new))
    return "gdk_pixbuf_new";
  if (!g_module_symbol(m, "gdk_pixbuf_unref", (gpointer *) &TileGtk_gdk_pixbuf_unref))
    return "gdk_pixbuf_unref";
  return 0;
}; /* TileGtk_InitialiseSymbols_gdk_pixbuf */


const char* TileGtk_InitialiseSymbols_gdk_pixbuf_xlib(const char *file_name) {
  GModule *m = g_module_open(file_name, G_MODULE_BIND_LAZY);
  if (!m) return "module_open";
  if (!g_module_symbol(m, "gdk_pixbuf_xlib_render_to_drawable", (gpointer *) &TileGtk_gdk_pixbuf_xlib_render_to_drawable))
    return "gdk_pixbuf_xlib_render_to_drawable";
  if (!g_module_symbol(m, "xlib_rgb_init", (gpointer *) &TileGtk_xlib_rgb_init))
    return "xlib_rgb_init";
  return 0;
}; /* TileGtk_InitialiseSymbols_gdk_pixbuf_xlib */


const char* TileGtk_InitialiseSymbols_glib(const char *file_name) {
  GModule *m = g_module_open(file_name, G_MODULE_BIND_LAZY);
  if (!m) return "module_open";
  if (!g_module_symbol(m, "g_free", (gpointer *) &TileGtk_g_free))
    return "g_free";
  if (!g_module_symbol(m, "g_hash_table_get_keys", (gpointer *) &TileGtk_g_hash_table_get_keys))
    return "g_hash_table_get_keys";
  if (!g_module_symbol(m, "g_malloc", (gpointer *) &TileGtk_g_malloc))
    return "g_malloc";
  if (!g_module_symbol(m, "g_malloc0", (gpointer *) &TileGtk_g_malloc0))
    return "g_malloc0";
  if (!g_module_symbol(m, "g_option_context_add_main_entries", (gpointer *) &TileGtk_g_option_context_add_main_entries))
    return "g_option_context_add_main_entries";
  if (!g_module_symbol(m, "g_option_context_new", (gpointer *) &TileGtk_g_option_context_new))
    return "g_option_context_new";
  if (!g_module_symbol(m, "g_strfreev", (gpointer *) &TileGtk_g_strfreev))
    return "g_strfreev";
  return 0;
}; /* TileGtk_InitialiseSymbols_glib */


const char* TileGtk_InitialiseSymbols_gobject(const char *file_name) {
  GModule *m = g_module_open(file_name, G_MODULE_BIND_LAZY);
  if (!m) return "module_open";
  if (!g_module_symbol(m, "g_object_get", (gpointer *) &TileGtk_g_object_get))
    return "g_object_get";
  if (!g_module_symbol(m, "g_object_unref", (gpointer *) &TileGtk_g_object_unref))
    return "g_object_unref";
  return 0;
}; /* TileGtk_InitialiseSymbols_gobject */


const char* TileGtk_InitialiseSymbols_gtk(const char *file_name) {
  GModule *m = g_module_open(file_name, G_MODULE_BIND_LAZY);
  if (!m) return "module_open";
  if (!g_module_symbol(m, "gtk_adjustment_new", (gpointer *) &TileGtk_gtk_adjustment_new))
    return "gtk_adjustment_new";
  if (!g_module_symbol(m, "gtk_adjustment_set_value", (gpointer *) &TileGtk_gtk_adjustment_set_value))
    return "gtk_adjustment_set_value";
  if (!g_module_symbol(m, "gtk_arrow_new", (gpointer *) &TileGtk_gtk_arrow_new))
    return "gtk_arrow_new";
  if (!g_module_symbol(m, "gtk_border_free", (gpointer *) &TileGtk_gtk_border_free))
    return "gtk_border_free";
  if (!g_module_symbol(m, "gtk_button_get_relief", (gpointer *) &TileGtk_gtk_button_get_relief))
    return "gtk_button_get_relief";
  if (!g_module_symbol(m, "gtk_button_new", (gpointer *) &TileGtk_gtk_button_new))
    return "gtk_button_new";
  if (!g_module_symbol(m, "gtk_button_set_relief", (gpointer *) &TileGtk_gtk_button_set_relief))
    return "gtk_button_set_relief";
  if (!g_module_symbol(m, "gtk_check_button_new", (gpointer *) &TileGtk_gtk_check_button_new))
    return "gtk_check_button_new";
  if (!g_module_symbol(m, "gtk_combo_box_entry_new", (gpointer *) &TileGtk_gtk_combo_box_entry_new))
    return "gtk_combo_box_entry_new";
  if (!g_module_symbol(m, "gtk_combo_box_new", (gpointer *) &TileGtk_gtk_combo_box_new))
    return "gtk_combo_box_new";
  if (!g_module_symbol(m, "gtk_container_add", (gpointer *) &TileGtk_gtk_container_add))
    return "gtk_container_add";
  if (!g_module_symbol(m, "gtk_disable_setlocale", (gpointer *) &TileGtk_gtk_disable_setlocale))
    return "gtk_disable_setlocale";
  if (!g_module_symbol(m, "gtk_entry_new", (gpointer *) &TileGtk_gtk_entry_new))
    return "gtk_entry_new";
  if (!g_module_symbol(m, "gtk_fixed_new", (gpointer *) &TileGtk_gtk_fixed_new))
    return "gtk_fixed_new";
  if (!g_module_symbol(m, "gtk_frame_new", (gpointer *) &TileGtk_gtk_frame_new))
    return "gtk_frame_new";
  if (!g_module_symbol(m, "gtk_hpaned_new", (gpointer *) &TileGtk_gtk_hpaned_new))
    return "gtk_hpaned_new";
  if (!g_module_symbol(m, "gtk_hscale_new_with_range", (gpointer *) &TileGtk_gtk_hscale_new_with_range))
    return "gtk_hscale_new_with_range";
  if (!g_module_symbol(m, "gtk_hscrollbar_new", (gpointer *) &TileGtk_gtk_hscrollbar_new))
    return "gtk_hscrollbar_new";
  if (!g_module_symbol(m, "gtk_init_check", (gpointer *) &TileGtk_gtk_init_check))
    return "gtk_init_check";
  if (!g_module_symbol(m, "gtk_notebook_new", (gpointer *) &TileGtk_gtk_notebook_new))
    return "gtk_notebook_new";
  if (!g_module_symbol(m, "gtk_object_get", (gpointer *) &TileGtk_gtk_object_get))
    return "gtk_object_get";
  if (!g_module_symbol(m, "gtk_paint_arrow", (gpointer *) &TileGtk_gtk_paint_arrow))
    return "gtk_paint_arrow";
  if (!g_module_symbol(m, "gtk_paint_box", (gpointer *) &TileGtk_gtk_paint_box))
    return "gtk_paint_box";
  if (!g_module_symbol(m, "gtk_paint_box_gap", (gpointer *) &TileGtk_gtk_paint_box_gap))
    return "gtk_paint_box_gap";
  if (!g_module_symbol(m, "gtk_paint_check", (gpointer *) &TileGtk_gtk_paint_check))
    return "gtk_paint_check";
  if (!g_module_symbol(m, "gtk_paint_extension", (gpointer *) &TileGtk_gtk_paint_extension))
    return "gtk_paint_extension";
  if (!g_module_symbol(m, "gtk_paint_flat_box", (gpointer *) &TileGtk_gtk_paint_flat_box))
    return "gtk_paint_flat_box";
  if (!g_module_symbol(m, "gtk_paint_focus", (gpointer *) &TileGtk_gtk_paint_focus))
    return "gtk_paint_focus";
  if (!g_module_symbol(m, "gtk_paint_handle", (gpointer *) &TileGtk_gtk_paint_handle))
    return "gtk_paint_handle";
  if (!g_module_symbol(m, "gtk_paint_option", (gpointer *) &TileGtk_gtk_paint_option))
    return "gtk_paint_option";
  if (!g_module_symbol(m, "gtk_paint_resize_grip", (gpointer *) &TileGtk_gtk_paint_resize_grip))
    return "gtk_paint_resize_grip";
  if (!g_module_symbol(m, "gtk_paint_shadow", (gpointer *) &TileGtk_gtk_paint_shadow))
    return "gtk_paint_shadow";
  if (!g_module_symbol(m, "gtk_paint_slider", (gpointer *) &TileGtk_gtk_paint_slider))
    return "gtk_paint_slider";
  if (!g_module_symbol(m, "gtk_progress_bar_new", (gpointer *) &TileGtk_gtk_progress_bar_new))
    return "gtk_progress_bar_new";
  if (!g_module_symbol(m, "gtk_progress_bar_set_bar_style", (gpointer *) &TileGtk_gtk_progress_bar_set_bar_style))
    return "gtk_progress_bar_set_bar_style";
  if (!g_module_symbol(m, "gtk_progress_bar_set_fraction", (gpointer *) &TileGtk_gtk_progress_bar_set_fraction))
    return "gtk_progress_bar_set_fraction";
  if (!g_module_symbol(m, "gtk_progress_bar_set_orientation", (gpointer *) &TileGtk_gtk_progress_bar_set_orientation))
    return "gtk_progress_bar_set_orientation";
  if (!g_module_symbol(m, "gtk_range_get_adjustment", (gpointer *) &TileGtk_gtk_range_get_adjustment))
    return "gtk_range_get_adjustment";
  if (!g_module_symbol(m, "gtk_rc_get_default_files", (gpointer *) &TileGtk_gtk_rc_get_default_files))
    return "gtk_rc_get_default_files";
  if (!g_module_symbol(m, "gtk_rc_get_style", (gpointer *) &TileGtk_gtk_rc_get_style))
    return "gtk_rc_get_style";
  if (!g_module_symbol(m, "gtk_rc_get_theme_dir", (gpointer *) &TileGtk_gtk_rc_get_theme_dir))
    return "gtk_rc_get_theme_dir";
  if (!g_module_symbol(m, "gtk_rc_reparse_all_for_settings", (gpointer *) &TileGtk_gtk_rc_reparse_all_for_settings))
    return "gtk_rc_reparse_all_for_settings";
  if (!g_module_symbol(m, "gtk_rc_reset_styles", (gpointer *) &TileGtk_gtk_rc_reset_styles))
    return "gtk_rc_reset_styles";
  if (!g_module_symbol(m, "gtk_rc_set_default_files", (gpointer *) &TileGtk_gtk_rc_set_default_files))
    return "gtk_rc_set_default_files";
  if (!g_module_symbol(m, "gtk_settings_get_default", (gpointer *) &TileGtk_gtk_settings_get_default))
    return "gtk_settings_get_default";
  if (!g_module_symbol(m, "gtk_statusbar_new", (gpointer *) &TileGtk_gtk_statusbar_new))
    return "gtk_statusbar_new";
  if (!g_module_symbol(m, "gtk_style_apply_default_background", (gpointer *) &TileGtk_gtk_style_apply_default_background))
    return "gtk_style_apply_default_background";
  if (!g_module_symbol(m, "gtk_style_attach", (gpointer *) &TileGtk_gtk_style_attach))
    return "gtk_style_attach";
  if (!g_module_symbol(m, "gtk_style_lookup_color", (gpointer *) &TileGtk_gtk_style_lookup_color))
    return "gtk_style_lookup_color";
  if (!g_module_symbol(m, "gtk_toolbar_new", (gpointer *) &TileGtk_gtk_toolbar_new))
    return "gtk_toolbar_new";
  if (!g_module_symbol(m, "gtk_vpaned_new", (gpointer *) &TileGtk_gtk_vpaned_new))
    return "gtk_vpaned_new";
  if (!g_module_symbol(m, "gtk_vscale_new_with_range", (gpointer *) &TileGtk_gtk_vscale_new_with_range))
    return "gtk_vscale_new_with_range";
  if (!g_module_symbol(m, "gtk_vscrollbar_new", (gpointer *) &TileGtk_gtk_vscrollbar_new))
    return "gtk_vscrollbar_new";
  if (!g_module_symbol(m, "gtk_widget_destroy", (gpointer *) &TileGtk_gtk_widget_destroy))
    return "gtk_widget_destroy";
  if (!g_module_symbol(m, "gtk_widget_realize", (gpointer *) &TileGtk_gtk_widget_realize))
    return "gtk_widget_realize";
  if (!g_module_symbol(m, "gtk_widget_set_size_request", (gpointer *) &TileGtk_gtk_widget_set_size_request))
    return "gtk_widget_set_size_request";
  if (!g_module_symbol(m, "gtk_widget_size_request", (gpointer *) &TileGtk_gtk_widget_size_request))
    return "gtk_widget_size_request";
  if (!g_module_symbol(m, "gtk_widget_style_get", (gpointer *) &TileGtk_gtk_widget_style_get))
    return "gtk_widget_style_get";
  if (!g_module_symbol(m, "gtk_window_new", (gpointer *) &TileGtk_gtk_window_new))
    return "gtk_window_new";
  return 0;
}; /* TileGtk_InitialiseSymbols_gtk */

#endif /* TILEGTK_LOAD_GTK_DYNAMICALLY */
